services:
  # Base de Datos
  # mongodb:
  #   image: mongo:latest
  #   container_name: spotify_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

  # Backend (FastAPI)
  backend:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: spotify_backend
    ports:
      - "8000:8000"
    env_file:
      - ./src/api/.env
    # depends_on:
    #   - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=spotify_mood_db

  # Frontend (React/Vite)
  frontend:
    build:
      context: ./frontend
    container_name: spotify_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    # depends_on:
    #   - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  # seeder:
  #   build:
  #     context: ./src/api
  #   command:
  #     python ./app/src/api/seed.py
  #   # depends_on:
  #   #   - mongodb
  #   volumes:
  #     - ./src/api:/code/app/src/api
  #   restart: "no"

volumes:
  mongo-data:
