services:
  web:
    build: 
      context: .
      dockerfile: src/api/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/code/app/src/api
      - data:/data
    depends_on:
      - mongodb
    env_file: .env.example
    restart: always
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    env_file: .env.example
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  seeder1:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    command:
      python ./app/src/api/seed.py
    depends_on:
      - mongodb
    volumes:
      - ./src/api:/code/app/src/api
    env_file:
      .env.example
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge
  
volumes:
  mongo_data:
  data:
