services:
  web:
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        requirements_file: requirements.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/code/app/api
      - data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  seeder:
    build:
      context: ./api
    command:
      python ./api/seed.py
    depends_on:
      - mongodb
    volumes:
      - .:/code
    env_file:
      .env
    networks:
      - app-network
    restart: "no"

networks:
  app-network:
    driver: bridge
  
volumes:
  mongo_data:
  data:
